### ISSUE TITLE
Where to find the 121GW firmware

### ISSUE THREAD

**Issue by ooxi** [EEVblog/EEVblog-121GW#1]
In one of your videos you are talking about the 121GW being hackable by providing a JTAG interface to the main SAMD processor. Are you planning on open sourcing the firmware of the multimeter, too?

I would be very interested in seeing how such a device works internally :-)

Nevertheless :+1: for the great work!

**Comment by EEVblog** [comment]
Sorry no plan to open source the firmware. This is not my decision BTW.

David L. Jones
www.eevblog.com
The Electronics Engineering Video Blog

**Comment by ooxi** [comment]
:disappointed:

Thanks for the fast feedback anyway!

**Comment by flarn2006** [comment]
Whose decision was it and why did they make it? Aren't you in charge?

**Comment by EEVblog** [comment]
The firmware is not open source.
UEi wrote and own the software, their decision, I have no legal claim to it.

David L. Jones
www.eevblog.com
The Electronics Engineering Video Blog
